### ISSUE TITLE
CFN template created and Running But No Hash rate

### ISSUE THREAD

**Issue by gold10star** [mludvig/aws-ethereum-miner#10]
Cloud Formation Template uploaded and running. But i couldn't get any active workers and hash rate.

I have replaced my ETH wallet address and checked the miner address in ethermine, No active workers. I did connected SSH client to the instance.

Now how to check whether the mining starts on the instance or not? If not how to troubleshoot. Kindly help.

**Comment by mludvig** [comment]
You can check the logs in `/tmp/ethminer.log` on each instance.
