### ISSUE TITLE
Security Group(s) not linked to the VPCs in Auto Scaling Group

### ISSUE THREAD

**Issue by c5huracan** [mludvig/aws-ethereum-miner#12]
Hi Michael.

Getting the following message when CF is trying to create MinerAsg:

One or more security groups in the launch template are not linked to the VPCs configured in the Auto Scaling group (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: c5e48098-77fd-4082-a5cc-96cbf8bb4061; Proxy: null)

Tried searching on the message and reviewing the docs to no avail -- any assistance is appreciated!

c5

**Comment by mludvig** [comment]
When creating the stack make sure that the selected **Subnets** belong to the selected **VPC**. 

If you've got multiple VPCs in your region you may have inadvertently selected a Subnet from a VPC different than the one selected in the VpcId stack parameter.

Please reopen if it still doesn't work after re-checking these stack parameters.

**Comment by mludvig** [comment]
Actually ... I have added [`template-eth-default-vpc.yml`](../blob/master/template-eth-default-vpc.yml) that you can use without specifying the VPC and Subnets.

**Comment by c5huracan** [comment]
> Actually ... I have added [`template-eth-default-vpc.yml`](../blob/master/template-eth-default-vpc.yml) that you can use without specifying the VPC and Subnets.

Thank you sir! Now with a few clicks, I can lose money at scale ;-)
