### ISSUE TITLE
Enable CPU Monero mining on Eth miners

### ISSUE THREAD

**Issue by LaZyDK** [mludvig/aws-ethereum-miner#16]
I want to propose that we also use the CPU resources on these spot instances while mining Ethereum. 
This can be done by spinning up something like XMRig and connecting it to a Monero wallet.

**Comment by mludvig** [comment]
I played with `xmrig` running in parallel with `ethminer` but only earned a few cents per day. Looks like a waste of time. Perhaps a different CPU-minable coin?

**Comment by LaZyDK** [comment]
Thanks for testing. I believe that you are right - it is too little of a gain to mess with. Just more parts that can break.
