### ISSUE TITLE
The Cloudformation Stack does not seem to work on AWS G5

### ISSUE THREAD

**Issue by TheClone77** [mludvig/aws-ethereum-miner#18]
Any idea why the stack does not work on the new g5.xlarge instance type?

**Comment by mludvig** [comment]
Apparently the DeepLearning AMI is not compatible with the new G5, the NVidia driver doesn't load. I'm trying to find a better one.

**Comment by mludvig** [comment]
Does the new AMI work for you? Seems ok to me...

**Comment by TheClone77** [comment]
Yes, it works well.
