### ISSUE TITLE
Getting an error when starting G5.xlarge

### ISSUE THREAD

**Issue by ruslan-abrayev** [mludvig/aws-ethereum-miner#22]
Hi! g5 instance does not start, but everything is OK with the instance by default g4dn
![image](https://user-images.githubusercontent.com/29862417/143779830-7ae179a5-34fb-4921-a84a-ec11b98ad517.png)

**Comment by mludvig** [comment]
Most likely you're in a region where G5 is not supported. At the moment to use G5 you must be in us-east-1 (N. Virginia), us-west-2 (Oregon) or eu-west-1 (Ireland).
