### ISSUE TITLE
Error on ASG - UnfulfillableCapacity

### ISSUE THREAD

**Issue by frantisekrokusek** [mludvig/aws-ethereum-miner#23]
Hi Michael,

First thanks for this awesome template!

I am getting those errors, no matter the configuration...

> Launching a new EC2 instance. Status Reason: Could not launch Spot Instances. UnfulfillableCapacity - Unable to fulfill capacity due to your request configuration. Please adjust your request and try again. Launching EC2 instance failed.

>  Status Reason: Could not launch Spot Instances. InvalidFleetConfiguration - Your requested instance type (p3.8xlarge) is not supported in your requested Availability Zone (us-east-2c). Launching EC2 instance failed.

- us-east-2a, us-east-2b, us-east-2c

**Comment by mludvig** [comment]
Hi Frantisek, it could be a number of reasons:

* Wait a bit longer. The ASG tries different combinations of _instance types_ and _availability zones_ and it may take ~30 mins or more to find one that’s available. 

* Have you got high enough _Service limits_? You can increase them using `tools/incease-limits.sh` for each different instance type. 

* Try a _different region_, instance availability varies a lot between the regions. Try us-east-1, or us-west-2 that have the new g5.xlarge. 

Hope that helps :)

**Comment by frantisekrokusek** [comment]
Thanks for your answer!

I indeed tried:
- changing region:  oregon and ohio
- waiting hours...

I will try to increase service limits.

**Comment by mludvig** [comment]
In Oregon you can also enable the Los Angeles local zone - it usually has g4dn capacity available.
 
See here for the steps: [Instnace g4dn.xlarge not starting](https://github.com/mludvig/aws-ethereum-miner/issues/1#issuecomment-958753404)

Also check out my article on Medium with some more info: [Mining Ethereum on AWS — is it worth it?](https://michael-ludvig.medium.com/mining-ethereum-on-aws-is-it-worth-it-f13645c12eec)

**Comment by frantisekrokusek** [comment]
Thank you saddly I still can't figure out why it won't start...

**Comment by frantisekrokusek** [comment]
I am trying now to create a spot request manually and launch it myself.

**Comment by frantisekrokusek** [comment]
Ok I think I know what's the issue.. I have all spot requests limits to zero for G and P instance types! 🤯  Why is that?

**Comment by mludvig** [comment]
That's because that's the default for new accounts. See my comment in the first response ;)

> Have you got high enough Service limits? You can increase them using `tools/increase-quotas.sh` for each different instance type.

Simply run that `tools/increase-quotas.sh g4dn` from _AWS CloudShell_ and it will raise the support requests to increase the quotas in all the regions where _g4dn_ is available (this limit increase is valid for _g5_ as well). Then do the same for _p3_. Start with the default - increase to 64 and once they approve it take it a step higher to e.g. 192. If you try to raise straight from 0 to 192 they may take a long time to approve it.

**Comment by frantisekrokusek** [comment]
Waiting for approval right now!

**Comment by mludvig** [comment]
Closing, hope that the limit increase sorted the issues.

**Comment by frantisekrokusek** [comment]
Actually, AWS refused to increase my limits...

**Comment by mludvig** [comment]
You can try smaller limits, e.g. 16 instead of the default 64 and only in one or two regions (e.g. us-east-1, us-west-2). You can do it manually through the support centre. There is a high demand for GPU instances so they're sometimes reluctant, esp with new accounts. Good luck with that :)

**Comment by frantisekrokusek** [comment]
I tried to increase to 4 to try the `g5.xlarge`
