### ISSUE TITLE
Support for RVN?

### ISSUE THREAD

**Issue by mastermind1970** [mludvig/aws-ethereum-miner#24]
I read your article and another persons article about this setup and its really amazing how you made all this work so nicely.  Could this be adapted for mind Ravencoin?  I know it's probably not profitable, but the gamble is that it could become profitable at some point, so accumulating some coin would be nice.  In fact, since we are on the subject, it would be cool to have a config file that would let you choose the miner to use for a particular coin.  I'd love to mine a few of the less popular coins and see the results.  Sadly, I am not a coder. :)

**Comment by mludvig** [comment]
It can indeed be adopted for RVN but at the moment it's not on my todo list. The thing is that there are _heaps_ of different coins, each one is mined with a different software, there are different pools, address formats, etc. It's not practical to support it all through a universal template.

If you want to modify the template for RVN  clone this repository and update the `LaunchTemplate` -> `UserData` section (around line 370 in `template-eth-default-vpc.yml`) with the steps needed for Ravencoin mining. It shouldn't be too difficult.

However I wouldn't bother and if anything mine to ETH while you can. Once ETH 2.0 is here mining will no longer be possible, see: https://michael-ludvig.medium.com/mining-ethereum-on-aws-is-it-worth-it-f13645c12eec
