### ISSUE TITLE
Instance filter hanging when creating CloudFormation Stack

### ISSUE THREAD

**Issue by cabrila** [mludvig/aws-ethereum-miner#28]
Hi,
I have tried running your script, but it seems to hang at the creation of the InstanceFilter (after an hour the creation was rolled back):
![image](https://user-images.githubusercontent.com/53343916/147989325-0b78a8f9-e913-461d-b3ff-ac57721d7000.png)

The parameters I use are:
![image](https://user-images.githubusercontent.com/53343916/147989386-918cae48-ea57-47d3-8599-c33f761a6dba.png)

I hope you can help

**Comment by mludvig** [comment]
What region was that? Also is there anything in the CloudWatch logs for that Lambda?

**Comment by cabrila** [comment]
It is the same problem in all regions. Have tried in Ohio, N. Virginia, Oregon etc

The rollback also failed with this error:
![image](https://user-images.githubusercontent.com/53343916/148116893-32bea196-3054-4226-861c-a618f1e78ee3.png)

The output in Cloudwatch is:
![image](https://user-images.githubusercontent.com/53343916/148116283-b6176b37-ff12-4e4d-8876-4d63421e9d9d.png)

**Comment by mludvig** [comment]
Did you modify the template in some way? Are you using the one from the project root, not the one from src/? Can you click on the [ERROR] line in cloudwatch to expand it?

**Comment by cabrila** [comment]
I have realized what the problem was.
I had copied the template and pasted it into the Stack Designer. But then the Stack can not get access to the Python scripts in the Lambda folder.

So now I have instead references the template scripts you have directed to in the Readme, and now it works

Thanks a lot for your support - Now I am just waiting to see how the mining goes

**Comment by mludvig** [comment]
Good to hear :)
