### ISSUE TITLE
Specify worker names in ethminer

### ISSUE THREAD

**Issue by jxu** [mludvig/aws-ethereum-miner#29]
For ethminer I noticed you can specify worker names using a format like `0x123456789012345678901234567890.Worker`. 

Idk if in cloud template you can get instance id or some kind of worker index. I guess you could just a random number for each worker so it'll show up in pools dashboards like ethermine.

**Comment by mludvig** [comment]
You can include the dot-suffix in the stack params if you want. I often use the region name and / or the account name as the worker name to know where I’m mining and where are problems.

**Comment by jxu** [comment]
Which parameter? EthWallet?

**Comment by mludvig** [comment]
Yes. Make EthWallet e.g. `0x1234…89.use2-acct99` for us-east-2 in account99.

**Comment by jxu** [comment]
Then every instance takes the same name right? My idea is that every instance get its own worker name. That is only for tracking pool-reported worker hashrates.
