### ISSUE TITLE
tools/service-limits.py 

### ISSUE THREAD

**Issue by John-G2** [mludvig/aws-ethereum-miner#30]
Hi, I'm trying to request a service limits increase in all relevant regions at once using your script tools/service-limits.py found here (https://github.com/mludvig/aws-ethereum-miner/blob/master/tools/increase-quotas.sh) but every time I open cloudshell and copy and paste I get a connection lost error with a sec... How do I paste that in to cloudshell in AWS..

Trying to increase as I'm hitting limitation on AWS EC2 instances..

Thanks for all your support in advance

**Comment by mludvig** [comment]
Why are you copy&pasting it? Clone the repo to CloudShell and run it from there:

```sh
[CloudShell] ~ $ git clone https://github.com/mludvig/aws-ethereum-miner.git
[CloudShell] ~ $ cd aws-ethereum-miner/tools
[CloudShell] ~/aws-ethereum-miner/tools $ ./increase-quotas.sh g4dn 16
```
