### ISSUE TITLE
I have created 9 stacks but I only see 1 worker

### ISSUE THREAD

**Issue by John-G2** [mludvig/aws-ethereum-miner#31]
Hi,

I need help to understand why I only see see 1 worker in ethermine.org even though I have created 3 stacks in each Zone in AWS.
<img width="1207" alt="Screen Shot 2022-01-12 at 10 50 47 AM" src="https://user-images.githubusercontent.com/97581679/149204863-81d1b7aa-7ceb-4b7d-b273-5b49934f6b5f.png">

**Comment by mludvig** [comment]
The instances don’t report a unique worker ID, they’re all summed up under “default”. Guessing from your rather high hashrate you’re certainly running a large number of instances and they all contributing to the “default” worker. Each instance typically does 25~50 MH/s so you’re likely running between 40 ~ 80 instances?

No worries it works as expected :)

**Comment by John-G2** [comment]
That's correct, I'm running about 40 instances and I just added another 40 but I keep hitting the limit and I tried using the your code to request more access and it keeps failing

**Comment by mludvig** [comment]
Unfortunately AWS is quite reluctant to approve GPU limits increase at the moment unless you've got a very good usecase (where crypto mining probably doesn't make the cut). It's the same with GCP and Azure - GPU shortage affects all the clouds.
