### ISSUE TITLE
Error: no usable mining device found

### ISSUE THREAD

**Issue by xp0s3d0** [mludvig/aws-ethereum-miner#32]
Why launching instance from aws gui with "launch gui":
manually selecting ami-0476917f2861069bf (us-east-1)
(but tried also with Amazon Linux 2 AMI with AMD Radeon Pro Driver)
g4adxlarge instance type
ssh into instance
downloading ethminer
launching ethminer and getting:
Error: no usable mining device found

**Comment by mludvig** [comment]
Where did you download ethminer from? Did you use the URL from the template? That one works for me.
In fact does the template work for you?

**Comment by xp0s3d0** [comment]
I dont think that the problem is ethminer version, if I try to use your script and change it for grabbing from official github other mining software like teamredminer it works. 
But if I try to launch an aws instance normally (using same ami that the yml script grabs) then i get error about no device found for mining regardless of mining software used. 
Also (if I dont remember wrong) I also tried another thing some days ago:
Launching a ec2 using your script starting mining and it worked fine, then entered the instance using session manager, stopped the miner, tried to restart it and get same error (no device found)

**Comment by mludvig** [comment]
Right, so when you use the template it works. That's what's important.

I can't really help you with compatibility issues with other software, other AMIs and other configurations, sorry. Use the template and be done with it :)
