### ISSUE TITLE
Enable GPU/CPU ZCash

### ISSUE THREAD

**Issue by quentingosset** [mludvig/aws-ethereum-miner#33]
Hey, thanks for this fabulous script that works without a hitch for eth! 
I would like to know if it is possible to activate CPU and GPU mining to mine Zcash?

Have you already tested it maybe?

**Comment by mludvig** [comment]
Hi, no I didn't test it - there are _far too many different coins_ and _far too many different miner programs_ for those coins. I can only provide some support if you use the template as is to mine ETH as that's a verified combination that's known to work. 

If you want to mine some other coin or use some other software by all means go ahead and modify the template to your needs. I won't be able to help much with any compatibility or stability issues though. :)
