### ISSUE TITLE
ETH Miner not running 

### ISSUE THREAD

**Issue by singularapp** [mludvig/aws-ethereum-miner#34]
hi there, 

many thanks for providing the template, I have applied it to our AWS Gd5 but it seems that its still not running although I can see the instance has been created successfully. Appreciate if you could enlighten us. 

<img width="1440" alt="Screen Shot 2022-02-08 at 11 53 26 AM" src="https://user-images.githubusercontent.com/89886391/152915131-7e6ee2ed-8c5a-48f7-85c5-c85bf96852dc.png">

Also,<img width="1419" alt="Screen Shot 2022-02-08 at 10 53 37 AM" src="https://user-images.githubusercontent.com/89886391/152909573-2b492e60-7464-4b07-884e-501b7d956848.png"> would like to apply this to Google Cloud of Alibaba Cloud if it can also be done there, Open for Collabs or custom work if you're open to it.

<img width="1144" alt="Screen Shot 2022-02-08 at 10 53 25 AM" src="https://user-images.githubusercontent.com/89886391/152909564-34e2b762-a5cc-4b7f-ad5b-f5df39e64ea3.png">

**Comment by mludvig** [comment]
Have the instances actually been started? Look at EC2 -> Instances and see if there are any. If not look into the AutoScaling Group down near the bottom on the EC2 page, and in the Activity tab see why it isn't starting the instances. Let me know what you find.

**Comment by singularapp** [comment]
Many thanks for your prompt reply Michael, I've just launched it under EC2 instances, not sure if I've configured it properly. Again truly appreciate your contribution to the community ! 
<img width="1419" alt="Screen Shot 2022-02-08 at 12 13 49 PM" src="https://user-images.githubusercontent.com/89886391/152917346-1bea62dc-3662-4292-b00e-c9c8a877042a.png">
<img width="1429" alt="Screen Shot 2022-02-08 at 12 14 56 PM" src="https://user-images.githubusercontent.com/89886391/152917365-1d49c7aa-4240-4b7f-bd1c-df14974beebc.png">

**Comment by mludvig** [comment]
Well you've launched t2.xlarge - that one doesn't have a GPU. It looks like the ASG couldn't create the G5G or G4dn instances.

- What region are you in?
- What does EC2 -> AutoScaling Groups -> Activity tab show? Any errors?
- Do you have high enough service limits for "G and VT spot instances" in the region?

**Comment by singularapp** [comment]
- Ohio (Which region will work best?)
- It seems that I haven't created an auto scaling group, where should I start?)
- How do we configure the service limits so it will start working?

**Comment by mludvig** [comment]
The CloudFormation template takes care of creating the AutoScaling Group. The screenshot above that says `CloudFormation > Stacks > ETHMINER` is the place to start. Click on the Resources tab there and look for `Asg` line. It will have a link to ETHMINER-Asg-{...} - click that and it will open the AutoScaling Group. There you'll have _Activities_ tab (or is it _Events_? I don't remember) - check that out to see why it didn't create the G5 or G4 instances.

BTW You can delete the t2.micro and t2.xlarge instances, they don't support ETH mining.

**Comment by singularapp** [comment]
I've followed the steps and recreated the
<img width="1324" alt="Screen Shot 2022-02-08 at 1 13 52 PM" src="https://user-images.githubusercontent.com/89886391/152922643-c9cecdba-397f-480a-be92-d073422eea04.png">
 stack with CloudFormation, heres what I'm seeing after clicking on Asg , kindly advise the next steps 
<img width="1280" alt="Screen Shot 2022-02-08 at 1 11 43 PM" src="https://user-images.githubusercontent.com/89886391/152922632-dbddda2d-8eeb-455d-b47c-458cbae0e127.png">

**Comment by singularapp** [comment]
Are you on Discord? Can we discuss this privately?  Looking to hire a custom work to ensure our AWS is optimized to run the mining at max hashrate. Here's our Discord ID: singular#1853

**Comment by mludvig** [comment]
Hi @singularapp sent you a discord friend request from MLu#3729
