### ISSUE TITLE
instance is running but not showing up in mining dashboard

### ISSUE THREAD

**Issue by ljonson12** [mludvig/aws-ethereum-miner#35]
the instance is runnng but after waiting 2 hours still no hashrate recorded.

**Comment by linschiller** [comment]
I have encountered the same issues.

**Comment by mludvig** [comment]
You can check 2 things:

1 - check the wallet address in the CloudFormation stack parameters. Then go to the stack Outputs tab and click the Dashboard URL.

2 - login to one of the instances (use the "Connect" button in top-right corner and then SSM Session) and run `cat /tmp/ethminer.log` - what does it say?
