### ISSUE TITLE
g4ad.16xlarge Launching Error

### ISSUE THREAD

**Issue by shyamphaddd** [mludvig/aws-ethereum-miner#39]
Error in Launching g4ad.16xlarge in the Canada and Ireland Region.

**Comment by mludvig** [comment]
What “error”? Provide details from AutoScaling Group -> Activity tab.

**Comment by shyamphaddd** [comment]
My Bad.

(Received response status [FAILED] from custom resource. Message returned: Error: None of the requested instance types is available in this region!)

The Instances are not available in the region.

**Comment by shyamphaddd** [comment]
By the way which is the best instance to mine crypto currently. I've around 90000 credits available

**Comment by mludvig** [comment]
Which region and what instances are you trying when you're getting the error?

Email me at mludvig@logix.net.nz and we can have a chat.
