### ISSUE TITLE
1/2 checks passed

### ISSUE THREAD

**Issue by hermitico** [mludvig/aws-ethereum-miner#40]
Hi Michael,

I have three instances running, two with no issues (each with 2/2 checks passed), both g5.xlarge. But there is a g5g.xlarge with 1/2 checks passed.
Is that one running but in an unproductive way? Is AWS charging me for that one anyway?
I tried to reboot that instance but didn't solve the problem.

**Comment by hermitico** [comment]
Some extra info.
They are in N. Virginia.

* System reachability check passed
* Instance reachability check failed
Check failure at
2022/03/20 18:20 GMT-4 (about 13 hours)

**Comment by mludvig** [comment]
Right, it looks like there's some issue with g5g stability. It mines but eventually crashes and gets replaced. I'll have a look at it.

**Comment by mludvig** [comment]
For now I have disabled g5g.* from the template as they are somewhat unstable.
