### ISSUE TITLE
Consider different miner software to increase profitability

### ISSUE THREAD

**Issue by rockerptit** [mludvig/aws-ethereum-miner#42]
I can see that ethminer is being used. This is quite outdated and would cause low hashrate, hence low profitability.

I would suggest considering other miner software programs such as:

T-rex (NVIDIA GPUs only)
Teamredminer (AMD GPUs only)
lolminer (both GPUs)

**Comment by mludvig** [comment]
Hi, in my testing the hashrate is very closely comparable between the different miners. However feel free to update the template as you please :)
