### ISSUE TITLE
New AWS account they want me to use my current capacity before providing more capacity

### ISSUE THREAD

**Issue by hessio** [mludvig/aws-ethereum-miner#43]
I requested capacity upgrade but AWS declined saying I need use what I have been assigned before I am able to request more capacity. How do I update the cloudformation template to use up my current capacity?

**Comment by mludvig** [comment]
What are your current limits for "G spot" instances? If it's more than 0 simply create the CFN stack with some desired hashrate, e.g. 250 MH/s - it's the default - and let AWS fill it as best as it can. If you've got higher limits then increase the desired hashrate in the stack parameters. Let me know if helped.

**Comment by hessio** [comment]
my current limit is 0. They won't increase my limit for "G spot" instances. Is there a way to start mining without approval for these instances? Like a smaller sized instance which you have approval for when you first open an AWS account that way I will be using some instance then they might allow me to increase my limits. I tried with a hashrate of 250 MH/s

**Comment by hessio** [comment]
Do you have a guide to manually set up this instance rather than just using the cloud formation?

**Comment by mludvig** [comment]
Hi, without G or P instances limits you can’t mine. You need a GPU and these are the only instance types that offer it. You’ll have to convince AWS to raise your limits.

**Comment by hessio** [comment]
Oh ok that makes sense thanks, I'll keep trying :)

**Comment by boyesm** [comment]
Any luck with this @hessio ? I'm running into the same issue right now...

**Comment by mludvig** [comment]
What exactly does AWS require? I had limits increase requests declined due to lack of capacity but was never told to use what I had first before they approve more.
