### ISSUE TITLE
Instance type

### ISSUE THREAD

**Issue by hermitico** [mludvig/aws-ethereum-miner#45]
Hi Michael,

I was wondering if it would make sense to use a 3-yr ISP Effective Hourly (Linux) plan, which can be cheaper.
If so, can you set that option as a parameter?

Thanks

**Comment by mludvig** [comment]
Reserved instances are just a billing construct, not something that you set when creating the instance. To use RI start up the instances as on-demand and then in the Reserved instances console page buy the 3yr plan. 

You may be better off setting up a Compute Saving Plan rather then a Reserved Instance as it offers more flexibility to switch between different instance types. 

https://aws.amazon.com/savingsplans/compute-pricing/
