### ISSUE TITLE
Got it working manually 

### ISSUE THREAD

**Issue by woothok** [mludvig/aws-ethereum-miner#46]
Hey Michael,  
Great articles and background!   I appreciate it!

I got instances to successfully launch using your template, but they didn't produce any results.   I couldn't connect to them using SSM for some reason, so I couldn't really tell you what was going on.

What *did* work was to build the instance by hand, and add the ubuntu user to the "video" and "render" groups.  Does that make any sense?   If so, I'm not quite sure how to drop that into the YAML template, in which case I think I could create a new AMI.  

Will post back here as I learn more, but if you have any thoughts in the meantime they are most welcome!

best Regards,
Tom Wood

**Comment by mludvig** [comment]
Hi Tom, the template should create the instances fully configured. Since you couldn’t even SSM to them I suspect that your VPC may have a non-standard setup preventing outbound access from the instances. 

You may want to try the “custom vpc” templates and select the subnets manually.
