### ISSUE TITLE
Error with the ethminer stack 

### ISSUE THREAD

**Issue by Alextrem83** [mludvig/aws-ethereum-miner#50]
Hello 

Seems to have an error with my ethminer stack
deleted it by mistake ...

and when i re created it i have a problem with the lambda function 
tried to delete the lambda Function but won't let me do it either 

![image](https://user-images.githubusercontent.com/105794162/169041635-6f40a9e0-f81c-49fd-8204-f96a7870d4d9.png)

Can anyone help me with this problem 

thanks

**Comment by Alextrem83** [comment]
![image](https://user-images.githubusercontent.com/105794162/169042112-dbcbb8ae-a537-43f4-8b37-3b7e941716d2.png)

**Comment by mludvig** [comment]
Do you still experience this issue? What region is it?

**Comment by Alextrem83** [comment]
Hello 

Thanks for your return 
It was in fact aws that flagged my account for suspicious activities and They asked me to secure my account before de flagging it 
Is has been resolved 

Kind regards

**Comment by mludvig** [comment]
Good to hear it’s resolved
