### ISSUE TITLE
Spot Instance not launching 

### ISSUE THREAD

**Issue by kiddkrypto** [mludvig/aws-ethereum-miner#51]
I am having the below error since i have launched the CFT. I have ran it for about 12 hours. I am not sure what config i can mess with to correct this. Can you help?
![Screen Shot 2022-05-25 at 11 16 54 PM](https://user-images.githubusercontent.com/62265829/170415235-c836e953-7fc7-4ea2-bd49-cd9c39fa1f77.png)

**Comment by mludvig** [comment]
Hi, what _region_ is it and what _instance types_ did you request? Do you have EC2 _service quotas_ high enough to run GPU instances? You can use `tools/list-quotas.sh` to check that.

**Comment by kiddkrypto** [comment]
This is in us-east-2. It seems that by default this region is set to 0. so i increased it to 10 to see if i get approved on that

**Comment by mludvig** [comment]
Once your GPU quotas are increased you should be able to start the miners. Reopen if it still won't work.
