### ISSUE TITLE
Documentation launche CF template using AWS Cli

### ISSUE THREAD

**Issue by d4op** [mludvig/aws-ethereum-miner#52]
Great CF template. 

is this cli correct?
aws cloudformation deploy --stack-name couldminer \ 
--template-file template-eth-default-vpc.yml \
--profile test-aws

just want to ask.

**Comment by mludvig** [comment]
Hey that's _almost_ correct. However you may want to change the wallet address (unless you want to mine into mine) and also will need to give it the permissions to create IAM role with `--capabilities CAPABILITY_IAM`. 

This should do:

```
ETH_WALLET=0x99b36B44cf319c9E0ed4619ee2050B21ECac2c15
aws --profile test-aws cloudformation create-stack \
    --stack-name cloudminer --capabilities CAPABILITY_IAM \
    --template-url https://s3.us-west-2.amazonaws.com/cnl4uehyq6/ethminer/template-eth-default-vpc.yml \
    --parameters ParameterKey=EthWallet,ParameterValue=${ETH_WALLET}
```

Or check out this snippet for a complete example that deploys to all the available regions:

https://gist.github.com/mludvig/d21b03baf53a5499626f1a786af7b6f7
