### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by kiddkrypto** [mludvig/aws-ethereum-miner#53]
Hello, 

Wanted to know if it were possible to add Zcash or any other coins that are offered in ethermine.org to be profitable using the existing CF template?

**Comment by mludvig** [comment]
The templates are open-source, you are welcome to update them as you see fit and add any other miners. However note that you can only make very very little on CPU mining and the added complexity isn't worth it. And there's no point adding another GPU miner as the GPU is fully utilised by Ethminer. It's all open source, feel free to change it as you want.
