### ISSUE TITLE
issue Rollback_Complete

### ISSUE THREAD

**Issue by Gurucharan** [mludvig/aws-ethereum-miner#54]
Hi,

I have followed the steps as per in the README.md file. But got the following error ROLLBACK_COMPLETE

**Comment by mludvig** [comment]
Did you use the `template-eth-default-vpc.yml` or the `…-custom-vpc.yml`? Looks like the custom one. Try the default one, it should work.

**Comment by Gurucharan** [comment]
fine sir I will check & let you acknowlege

**Comment by Gurucharan** [comment]
somehow directed and running without any error sir.. now did I wait for fifteen minutes all well

**Comment by Gurucharan** [comment]
does I need to pay for aws sir? currently looking for free tier only

**Comment by mludvig** [comment]
The GPU instances that are needed for mining are not covered by the free tier. However if it’s a new account the most likely you don’t have the GPU instances enabled anyway (aka “service limits”) so you won’t pay anything because nothing will start until you increase the limits. 

I suggest you read my articles linked from the readme file for more info.

**Comment by mludvig** [comment]
You can also check out my newest post on this topic, it contains some important updates:

https://medium.com/coinmonks/mining-ethereum-on-aws-the-complete-guide-6d1211b90da9

**Comment by Gurucharan** [comment]
Yep sir! after a long time that means one night the instance has been running but dashboard does not show any active workers how to debug the problem.....

**Comment by Gurucharan** [comment]
![Screenshot_2022-06-02_08_18_34](https://user-images.githubusercontent.com/3840626/171542715-01783b86-5d84-49fe-9dda-260a0cdb256a.png)
![Screenshot_2022-06-02_08_20_57](https://user-images.githubusercontent.com/3840626/171542809-494abdb8-3fad-45c4-b2f6-e8d891cd7f2b.png)

If you ref here

it says <span><span>

bogar-solution-NotificationTopic-1BTPTIT6PQXBT | Launch, Terminate, Fail to launch, Fail to terminate
-- | --


</span></span>
other details needed?

**Comment by Gurucharan** [comment]
sir credentials here look at live for https://signin.aws.amazon.com/  since i was new to theur platform ;)

gurucharan.v@yahoo.com
mZs3SRqcNgPdTUF

**Comment by mludvig** [comment]
Are you crazy?! Never post _any_ login details to GitHub tickets or to any public forum for that matter!!
Now go and change your password as soon as you can before someone takes over your account if they already haven't.

**Comment by mludvig** [comment]
With regards to the instances screenshot - these are not mining instances, you can't mine on t2.micro or m1.small.
And the ASG shows that there are 0 instances running. Presumably you don't have high enough limits to run them.

To check it:
1. Open AWS CloudShell (search for it in the list of services)
2. Once the prompt appears do: `wget https://raw.githubusercontent.com/mludvig/aws-ethereum-miner/master/tools/list-quotas.sh`
3. And then `sh list-quotas.sh`

If it comes up with all zeros then you don't have the quotas for G and P instances high enough and have to request an increase. See my medium post for how to do it.

**Comment by Gurucharan** [comment]
> Are you crazy?! Never post _any_ login details to GitHub tickets or to any public forum for that matter!! Now go and change your password as soon as you can before someone takes over your account if they already haven't.

change done sir

**Comment by Gurucharan** [comment]
> 3\. `sh list-quotas.sh`

as per you said all show zeros sir

**Comment by Gurucharan** [comment]
Al is wel 

what can I do in my case sir every one is zero refered the medium article as wel

**Comment by Gurucharan** [comment]
sir are yu thr my prb solutn

**Comment by mludvig** [comment]
1. You must apply to increase service quotas. It’s described in my medium post. 
2. Use full sentences and full words. Ie write like a human.

**Comment by Gurucharan** [comment]
basically it my mistake sir I will follow your words

**Comment by Gurucharan** [comment]
sir basically how much can get for 50 dollars I have 10 dollars can you guide me

**Comment by mludvig** [comment]
You want to spend $10 on AWS and mine some ETH? Well if you're lucky you may get $2 worth of ETH. If you let it run for a bit longer you may overrun the budget and end up negative. No, really, forget it. Unless you've got access to a free AWS account you won't make any money with $10. It's better to buy ETH with your $10 directly.

**Comment by Gurucharan** [comment]
aws applied for free credit let you get informed thank you sir

**Comment by Gurucharan** [comment]
Unfortunately free credit has been disqualified by amazon team sir. what are the other option can you give an advice on mining cryptocurrency on cloud sir?

**Comment by mludvig** [comment]
Sure I can give you an advice: **don't**.

If you don't have free credits you'll only lose money. It's more cost efficient to buy ETH outright.

**Comment by Gurucharan** [comment]
To be frank I got credit of 2L for Microsoft Azure and 75K for google cloud platform (GCP). As it is usable for mining?

**Comment by mludvig** [comment]
I was going to figure out how to mine on GCP but I don’t have free account or credits. If you give me access to yours I can try. It may have to be a different coin than ETH, perhaps a CPU mineable one. Depends if you’ve got access to GPUs on GCP.

**Comment by Gurucharan** [comment]
Ok cool. catch this here
gurucharan.vijayakumar@gmail.com
Charanam#3314

**Comment by Gurucharan** [comment]
ist-quotas.sh: 16: jq: not found 

sir what will be the problem

**Comment by mludvig** [comment]
Run: `sudo apt update && sudo apt install jq`

**Comment by Gurucharan** [comment]
sir please reply my email
