### ISSUE TITLE
Ethwallet changes once launched or doesn't properly set

### ISSUE THREAD

**Issue by jonathansmyth** [mludvig/aws-ethereum-miner#55]
I tried using two different wallets and the template changed to 0xf4b10f8D6F2659C0Eb2c2F559F62Fd90f0E853d6, which isn't my wallet. 

In the output panel, it shows the correct wallet as the hypertext link, but the actual link directs to the wallet above. 

When checking the log, it is directed to the 53d6 wallet. I tried setting up the template a number of times using different regions and the default/custom variants and regardless of what I do, it redirects to the wrong wallet. 

I tried using the default wallet, it did not change. I tried using two different wallets, and each time it changed to the above.

**Comment by mludvig** [comment]
That’s odd. So you’re saying that in the Outputs it _shows_ the correct address but when you click it it takes you to a wrong one?? Is that what you’re seeing?

Can you try from a different browser?

**Comment by jonathansmyth** [comment]
Yes, that's what happens -- and it appears that the mining is occurring for the wrong address. 

When I go to update the template, it shows the incorrect 0xf4b10f8D6F2659C0Eb2c2F559F62Fd90f0E853d6, but when I attempt to update it to my wallet it says I didn't make any changes. It's very weird. 

I'll give it a try with Edge, I'm using Chrome. I could share credentials with you if you wanted to take a look, you can email me at js@pop.bio.

**Comment by mludvig** [comment]
That’s indeed crazy, I’ve never heard of anything like this. 

Sounds like a malware or a virus or some malicious plugin in the other browser. 

I don’t think I can help with that, so closing the ticket. Reopen if I can be of any assistance :)
