### ISSUE TITLE
Workers not showing up although a total of 404 instances were created and active

### ISSUE THREAD

**Issue by MoAdelAbdelrahman** [mludvig/aws-ethereum-miner#56]
I created the stack and increased my limits, A total of 404 instances were created and running but workers are not shown? 
![31231](https://user-images.githubusercontent.com/58152328/173423527-2ba331a2-a204-4d3e-842d-4e83f2c50324.PNG)
![12321](https://user-images.githubusercontent.com/58152328/173423571-cd3c711d-010d-4be9-80b9-47ee5e9bc216.PNG)

**Comment by MoAdelAbdelrahman** [comment]
my account limits: 8 vcpu for X instances 
and 60 on demand.

**Comment by mludvig** [comment]
I see that you've changed the template to allow running **r5a.large** instances - these can't mine ETH. That's why they are not included in my template. You'll need to raise your service limits for P or G instances, these are the only one that can mine ETH.

**Comment by MoAdelAbdelrahman** [comment]
Thanks for the response, I managed to get an increase of 32Vcpus and I am
running your template now, I just want to ask, how to check the hashrate
reported by Ethimnier as stated in the repo?

Thank you

**Comment by mludvig** [comment]
What instance types has it started?

**Comment by mludvig** [comment]
Cool, you should now see that they are mining on ethermine.org. It takes 15 to 20 minutes before they show up and then the reported hashrate will ramp up slowly because ethermine calculates an average every 10 mins. Give it at least 2 hrs to let it stabilise.

**Comment by MoAdelAbdelrahman** [comment]
Thanks, I see now its stable on around 360MH/s, Any idea how to increase
that? Is it considered too low?

**Comment by MoAdelAbdelrahman** [comment]
Please help me it took a lot of money from me here already, instances types
are g4ad, g4dn, g5g.

**Comment by MoAdelAbdelrahman** [comment]
Also is it normal to be only having 1 worker for 11 instances??

**Comment by mludvig** [comment]
Hi @MoAdelAbdelrahman 

1. g4ad.xlarge can do ca 48 MH/s, both g5g.xlarge and g4dn.xlarge can do ca 25 MH/s. If you've got 11 instances running then with some mix of these instance types your 360 MH/s seems reasonable.

2. you will see one worker per region, it's expected.

3. eth mining is not profitable at the moment due to falling prices.

**Comment by MoAdelAbdelrahman** [comment]
Thank you so much for your response, one final question, and sorry for
disturbing you, is there a way of limiting the instance creation? like I
only need to initiate 5 instances not 11, how should I do that?

**Comment by MoAdelAbdelrahman** [comment]
Hello, Mr Micheal, I really need help, how much instances should be
running? Because there's 11 instances running here but it takes too much
money and makes around 5 usd per day as estimated in Ethermine dashboard.
What should I do?
