### ISSUE TITLE
Mine monero instead of ETH

### ISSUE THREAD

**Issue by MHemelHasan** [mludvig/aws-ethereum-miner#57]
Can It Possible to mine Monero? If yes How can I modify this

**Comment by mludvig** [comment]
You’ll have to replace the shell script in `src/user-data.txt` with your monero mining code and rebuild the templates with `make`. Pretty easy.

**Comment by MHemelHasan** [comment]
Can you help to do that? how can I rebuild the templates with make ? any documentation
