### ISSUE TITLE
Instances showing error after running a while

### ISSUE THREAD

**Issue by bhatiahardik** [mludvig/aws-ethereum-miner#6]
ail -f /tmp/ethminer.log
/lib/x86_64-linux-gnu/libc.so.6(+0x3efd0) [0x7f7fa1385fd0]
./ethminer() [0x493b8a]
./ethminer() [0x48d26a]
./ethminer() [0x48d54c]
./ethminer() [0x48fd86]
./ethminer() [0x48ff39]
./ethminer() [0x42a2d0]
./ethminer() [0x773aaf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f7fa1cf56db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f7fa1468a3f]

**Comment by mludvig** [comment]
I know, it happens sometimes. The runner script will restart them.
