### ISSUE TITLE
cant find devices

### ISSUE THREAD

**Issue by Newsbag** [mludvig/aws-ethereum-miner#60]
manually spun up the g4ad but software cannot find devices when it does 1101 files is missing and runs at 7mhs ..any tips on how to resolve this. dont want to use cloud formation templates .

**Comment by mludvig** [comment]
Without using the cloudformation template it’s hard to know your instance configuration. Can’t help sorry. 

Use the CFN template for a proven working config and if that doesn’t work either open a new ticket and we can have a look at it.

**Comment by Newsbag** [comment]
i am literally using the same commands and ami for this setup.. did u ever run this manually before setting up the cloudstack?

**Comment by mludvig** [comment]
Why not use the CFN template then?

**Comment by Newsbag** [comment]
i did deployed once after that it hasnt worked so i tried to manually iterate it..plus there are changes id like to make to the mining pool

**Comment by mludvig** [comment]
Does it work with an unmodified cfn template downloaded from the repo or using one of the deploy links in readme? If not what exactly is the error message?
