### ISSUE TITLE
Ethereum PoW Mining Phase Ends Soon - Ethereum Classic support

### ISSUE THREAD

**Issue by kadirozgun** [mludvig/aws-ethereum-miner#62]
Hi, the Ethereum PoW Mining phase will end in approximately 25 days will you share another template for us? I tried to update your template yet I failed.  We would appreciate if you do. Thanks.

**Comment by mludvig** [comment]
Hi, yes working on it. Watch this space and subscribe to the announcements mailing list at: https://eepurl.com/h2_oZ5

**Comment by mludvig** [comment]
**Ethereum Classic (ETC)** support has now been added to the templates. Deploy as usual and you'll have an option to choose whether to mine ETH or ETC in the stack parameters. 

Note that your ETC wallet address may be different from the ETH one, depending on your wallet.

**Comment by mludvig** [comment]
Done.
