### ISSUE TITLE
Can i use ETH address in my coinbase or FTX wallet or do i need to use metamask?

### ISSUE THREAD

**Issue by andreprawira** [mludvig/aws-ethereum-miner#63]
I'm using the default yml template, ran these 3 commands

- aws --region us-west-2 ec2 modify-availability-zone-group --group-name us-west-2-lax-1 --opt-in-status opted-in
- aws --region us-west-2 ec2 create-default-subnet --availability-zone us-west-2-lax-1a
 -aws --region us-west-2 ec2 create-default-subnet --availability-zone us-west-2-lax-1b

 and I chose g4ad.xlarge, 1000 hashrate, and spot in the CFT page. This is the output that I'm seeing in ASG page

![image](https://user-images.githubusercontent.com/42351199/189484889-772094a7-44f1-4627-a868-de110c2a0c6c.png)

Also 2 questions, do i need to use Metamask web wallet or can i use coinbase/ftx/binance exchange wallet? How do i know which hashrate i should set in there?

**Comment by mludvig** [comment]
1. The Auto-scaling group tries one AZ after another until it finds one where the requested instance type is supported and there’s capacity available. If you’ve got high enough service quotas you should eventually see your instances starting. 

2. You can use an exchange wallet but you have less control. Research custodial vs noncustodial wallets for more info.

**Comment by andreprawira** [comment]
I figured out the problem, turns out i dont have permission from AWS to boot up any G and P types instances, so i requested permission for that, but I need to ask how many instances should I request for? Cause the form asked for that

Also, what hashrate should I choose? Should i leave it by default?
And would we still be mining ETH once the merge is finished which i think in 10 days?

**Comment by mludvig** [comment]
Ask for 64 vCPU quota for G spot and P spot. That’s a good start. If they approve it you can ask for more. 

Leave the hashrate as is, it will go up to that limit but with lower vCPU quota it will in fact start fewer instances.

**Comment by andreprawira** [comment]
Now that the merge is completed, is there still any use for booting those instances for mining? Or do you know any other coins we could mine in AWS thats profitable?

**Comment by mludvig** [comment]
Hi, the templates have been updated for ETC (Ethereum Classic) mining. That still works after the ETH merge.

Just make sure that your ETC Wallet Address is correct, it may or may not be different from the ETH one, depends on you Wallet software.

Also AWS is now more willing to increase the GPU quotas, so you may have some luck there.
