### ISSUE TITLE
Shall I press some magic button?

### ISSUE THREAD

**Issue by trejder** [mludvig/aws-ethereum-miner#66]
Thank you for your fabulous guide. Though it seems pretty straightforward, I think that I have got stuck on some point.

Here is what I've done so far:

1. I have followed your guide, clicking _Launch to Default VPC_ next to `us-east-2 Ohio`.
2. I have clicked through the AWS form, providing my own wallet's address and not changing anything else.
3. CloudFormation says `UPDATE_COMPLETE` on my `etcm` stack, so I assume that I did everything as expected.

But, whenever I go to _Outputs_, as you advised, and click on [`DashboardUrl`](https://etc.ethermine.org/miners/0xb5a56CC0a0F7E23cbcE6004206Fd1e2430728fc2/dashboard) then I see _No active worker found_.

It's now 2,5 hour since my stack was created using your template, so I believe that some stats should already be visible.

Is creating a CloudFormation's stack, using your template, and bringing it to `UPDATE_COMPLETE` is really all that I have to do? There isn't any magic button that I must press to start the stack or bring some workers on-line?

**Comment by mludvig** [comment]
You can check a couple of things:

1. Do your instances actually run? Go to the EC2 console and then Instances and see if there are any (with name "etcm" - same as the stack name). If none are running you'll have to figure out why - go to Autoscaling Groups way down on the left hand side bar in the EC2 console and in the "etcm" activities tab see why they fail to launch.

2. If there are instances running but you don't see the anything in the ethermine dashboard you'll have to login to the instance and have a look. Select one of the instances in the EC2 console, and click Connect button up-right above the list of instances. Then choose the "Session Manager" tab and Connect and it should open a shell. From there you can do `less -r /tmp/etcminer.log` and see if it complains about anything.

3. If the etcminer.log file is not there it's worth figuring out why. Do `less -r /var/log/cloud-init-output.log` and look for _etcminer_ to see if there are any errors downloading or running it.

Let me know if you need any further help with that.

**Comment by mludvig** [comment]
1. You can use the `list-quotas.sh` script from the `tools/` folder. It will tell you which regions have GPU instance *quotas* available. The unit is vCPU.
2. You have to request quota increase - either through the console or using the `increase-quota.sh` script. Try a lower request in one or two regions first, e.g. 32 vCPUs. The AWS support may come back with some questions and request a justification.
3. You select it in the stack parameters. By default it's set to '*' which means any GPU instance type. You can change that to e.g. 'g5.*' or 'g5g.large' or a list of instances like 'g4.*,g5.*'.
4. You can't really control it in the stack but you can check the actual spend in Cost Explorer and in the Billing interface in general.
5. Metamask can use the same address for both ETH and ETC so no issues there. You don't have to have it running or set to one or the other while mining. Only when you want to spend or move the coins later you'll have to run it and select the right network.
6. Nope you can't mine on Lightsail, they have no GPU. This project makes mining really easy, all you need to do is convince the AWS Support to increase your GPU quotas (that's the hardest part). From there on it should just work.
Good luck :)

**Comment by trejder** [comment]
Thank you once again for all your support and answers. The issue has been resolved (so we can close this thread anytime we want now) by -- as you said -- convincing AWS to allocate additional quota.

The instances are working, with current computing power of 270.7 MH/s and average one nearing 300 MH/s.

The instances are working, the dashboard shows stats, however (just to feed your curiosity) as for right now mining ETC with your stack in Ohio is completely not profitable at all (at least in this moment). Total costs are as high as **115-120%** of total earnings.

My current dashboard summary says that I have incurred so far **0.02769 ETC**:

![image](https://user-images.githubusercontent.com/2903392/217753850-b0f91210-b3cd-42bd-9218-7ecb495bcd5a.png)

Which roughly equivalents to **45 USD**:

![image](https://user-images.githubusercontent.com/2903392/217753935-af9e1aba-1730-4978-b922-048bc1065b9b.png)

While total costs so far are **52.57 USD**:

![image](https://user-images.githubusercontent.com/2903392/217754180-39fd516a-adbb-4417-ad99-51e61f07dd2e.png)

These stats are just my feedback (and a kind of "thank you" to you) in case you'd like to update some of your articles. I will (as promised) be sending a more concreate token of gratitude at the end of this month.

**Comment by mludvig** [comment]
Hi, good to hear that you made it work. Yeah it's been some time since AWS mining was profitable. It still works out all right for people who have free AWS accounts or plenty of free credits (note that mining is against the credits T&C's though). For everyone else it's a losing game unfortunately.

**Comment by trejder** [comment]
Do you know what can be the reason for getting hashrate drop from initial 270 MH/s current (300 MH/s average) yesterday to just  36.7 MH/s current (99.9 MH/s average)? This looks like nearly 10x loss without any particular reason.
