### ISSUE TITLE
Template contains errors.: Template format error: At least one Resources member must be defined.

### ISSUE THREAD

**Issue by hmpargi** [mludvig/aws-ethereum-miner#7]
Hi,
While Validating template in cloudformation-yaml. i received this error and couldn't run the template. I have only updated my eith wallet address in yml. everything remain same. I am doing something wrong ?

 5/9/2021, 7:52:41 AM - Template contains errors.: Template format error: At least one Resources member must be defined.

**Comment by mludvig** [comment]
I guess a typo when you've updated the template.
