### ISSUE TITLE
Launch complete

### ISSUE THREAD

**Issue by txzhub** [mludvig/aws-ethereum-miner#85]
Could someone kindly answer.
It says launch complete. So thats good.

My understanding is that everything is converted to btc.

Is there a minimum amount of btc generated where is is deposited into the btc address we provided?

Can anyone tell me your experience.

**Comment by mludvig** [comment]
The mining pool dashboard will tell you what's the minimum payout amount. Usually around $10 worth of BTC.

Also check out https://github.com/mludvig/aws-crypto-miner for a better and more configurable miner template.

**Comment by txzhub** [comment]
Thanks. Where do i find the mining pool dashboard?
